Error_Exception: Include the cause of the exception as an parameter.
Including the cause of the exception will make it simpler to trace
exceptions through the program.